# Generated by Django 3.2.16 on 2023-01-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
