# Generated by Django 3.2.16 on 2023-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ncomments',
            field=models.IntegerField(default=0),
        ),
    ]
