# Generated by Django 3.2.16 on 2023-02-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_ncomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ncomments',
        ),
    ]
